FROM node:12-alpine

RUN npm i lerna -g --loglevel error
USER node

RUN mkdir /home/node/app
WORKDIR /home/node/app

EXPOSE 3000

ARG SERVICE
ENV SERVICE $SERVICE

COPY --chown=node:node package.json yarn.lock lerna.json tsconfig.json tsconfig.build.json .eslintrc.js .eslintignore ./

# TODO
# COPY --chown=node:node packages /home/node/app/packages
COPY --chown=node:node $SERVICE/package.json $SERVICE/yarn.* /home/node/app/$SERVICE/

RUN yarn

COPY --chown=node:node . .

CMD cd $SERVICE && yarn development
