{{- $adminSecret := include "hasura.adminSecret" . -}}
{{- $jwtSecret := include "hasura.jwtSecret" . -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hasura.fullname" . }}
type: Opaque
data:
  adminSecret: {{ $adminSecret | b64enc | quote }}
  jwt.secret: {{ $jwtSecret | b64enc | quote }}
  {{- if (fromJson $jwtSecret).key }}
  jwt.key: {{ (fromJson $jwtSecret).key | b64enc | quote }}
  {{- end }}