module.exports = {
  main: [
    'introduction',
    {
      'Getting started': [
        'getting-started/installation',
        'getting-started/configuration'
      ]
    },
    'comparison',
    'roadmap'
  ],
  artifacts: [
    'artifacts/index',
    {
      type: 'category',
      label: 'Helm Charts',
      items: [{ type: 'autogenerated', dirName: 'artifacts/charts' }]
    },
    {
      type: 'category',
      label: 'Docker',
      items: [
        {
          type: 'autogenerated',
          dirName: 'artifacts/docker'
        }
      ]
    },
    'artifacts/tilt',
    'artifacts/pulumi'
  ]
}
