{{- if .Values.ingress.enabled -}}
{{- $fullName := include "hasura.fullname" . -}}
{{- $hostname := include "hostname" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: hasura
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: "Host(`hasura.{{ $hostname }}`) && PathPrefix(`/`)"
      services:
        - name: {{ $fullName }}
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: hasura-tls
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: "Host(`hasura.{{ $hostname }}`) && PathPrefix(`/`)"
      services:
        - name: {{ $fullName }}
          port: 80
  tls:
    secretName: {{ .Release.Name }}-cert
{{- end }}
