create schema metadata;
create view metadata.check_constraint as select * from hdb_catalog.hdb_check_constraint;
create view metadata.computed_field as select * from hdb_catalog.hdb_computed_field;
create view metadata.custom_type as select * from hdb_catalog.hdb_custom_types;
create view metadata.foreign_key_constraint as select * from hdb_catalog.hdb_foreign_key_constraint;
create view metadata.function as select * from hdb_catalog.hdb_function;
create view metadata.function_agg as select * from hdb_catalog.hdb_function_agg;
create view metadata.permission_agg as select * from hdb_catalog.hdb_permission_agg;
create view metadata.primary_key as select * from hdb_catalog.hdb_primary_key;
create view metadata.relationship as select * from hdb_catalog.hdb_relationship;
create view metadata.role as select * from hdb_catalog.hdb_role;
create view metadata.table as select * from hdb_catalog.hdb_table where is_system_defined = false;
create view metadata.unique_constraint as select * from hdb_catalog.hdb_unique_constraint;
create view metadata.version as select * from hdb_catalog.hdb_version;
create view metadata.table_info as select * from information_schema.tables;
create view metadata.column_info as select * from information_schema.columns;
create view metadata.schema_info as select * from information_schema.schemata;
create view metadata.view_info as select * from information_schema.views;
