yaml = helm(
  'helm',
  # The release name, equivalent to helm --name
  name='test',
  # The namespace to install in, equivalent to helm --namespace
  namespace='default',
  # The values file to substitute into the chart.
  values=['./helm/values-dev.yaml'],
  )
k8s_yaml(yaml)
# docker_build ( ref , context , build_args={} , dockerfile='Dockerfile' , dockerfile_contents='' , live_update=[] , match_in_env_vars=False , ignore=[] , only=[] , entrypoint=[] , target='' , ssh='' , network='' , secret='' , extra_tag='' , container_args=None , cache_from=[] , pull=False ) 

docker_build('platyplus/frontend', '..', dockerfile='frontend/Dockerfile-development')
docker_build('hasura', 'hasura')
docker_build('hbp', 'hbp')
